Repository Yeoun-project/yeoun, pull requests merged in 2025-05, with the labels that each got.

#73 [Feat] 질문 모음 페이지
  frontend/src/components/modal/ConfirmModal.tsx
  frontend/src/components/nav/BottomTabBar.tsx
  frontend/src/pages/AddQuestionPage.tsx
  frontend/src/pages/QuestionListPage.tsx
  frontend/src/routes/router.tsx
  frontend/src/services/api/question/getQuestions.ts
Labels: FE, ✨ Feature

#74 FEAT: 회원이 오늘 질문을 작성했는지 유무 조회 API 추가
  backend/src/main/java/yeoun/question/domain/repository/QuestionRepository.java
  backend/src/main/java/yeoun/question/dto/response/CheckTodayQuestionWrittenResponse.java
  backend/src/main/java/yeoun/question/presentation/QuestionController.java
  backend/src/main/java/yeoun/question/service/QuestionService.java
Labels: BE, ✨ Feature

#75 [Feat] 답변모음 페이지
  frontend/package.json
  frontend/public/icons/bigX.svg
  frontend/public/icons/filledHeart.svg
  frontend/public/icons/heart.svg
  frontend/public/icons/report.svg
  frontend/public/icons/smallX.svg
  frontend/src/components/answerList/AnswerItem.tsx
  frontend/src/components/modal/AvailableModal.tsx
  frontend/src/components/modal/RegisterModal.tsx
  frontend/src/components/modal/ReportModal.tsx
  frontend/src/hooks/queries/useCommentGroup.ts
  frontend/src/hooks/queries/useGetQuestionDetail.ts
  frontend/src/pages/question/QuestionCommentPage.tsx
  frontend/src/routes/router.tsx
  frontend/src/services/api/comment/commentLike.ts
  frontend/src/services/api/comment/getComment.ts
  frontend/src/services/api/question/getQuestionDetail.ts
  frontend/src/type/comment.d.ts
  frontend/src/utils/commentGroup.ts
  package-lock.json
Labels: FE, ✨ Feature

#78 feat: 오늘의 질문 답변 수정 API 추가
  backend/src/main/java/yeoun/exception/CustomExceptionHandler.java
  backend/src/main/java/yeoun/question/domain/QuestionHistory.java
  backend/src/main/java/yeoun/question/presentation/TodayQuestionController.java
  backend/src/main/java/yeoun/question/service/TodayQuestionService.java
Labels: BE, ✨ Feature

#87 FEAT: 내가 답변한 오늘의 질문 리스트 조회 API 추가
  backend/src/main/java/yeoun/question/domain/repository/QuestionHistoryRepository.java
  backend/src/main/java/yeoun/question/dto/response/TodayQuestionListResponse.java
  backend/src/main/java/yeoun/question/presentation/TodayQuestionController.java
  backend/src/main/java/yeoun/question/service/TodayQuestionService.java
Labels: BE, ✨ Feature

#90 FIX: 오늘의 질문 조회 시 createTime, hasComment 기준이 잘못된 버그 수정
  backend/src/main/java/yeoun/question/domain/repository/TodayQuestionRepository.java
  backend/src/main/java/yeoun/question/dto/response/TodayQuestionResponse.java
  backend/src/main/java/yeoun/question/service/TodayQuestionService.java
Labels: 🐞 Bug, BE, 🔨 Refactor

#91 FEAT: 금지어 검증 규칙 수정사항 반영
  backend/src/main/java/yeoun/question/service/ForbiddenWordService.java
  backend/src/test/java/yeoun/question/service/ForbiddenWordServiceTest.java
Labels: BE, ✨ Feature

#92 FEAT: 오늘의 질문 상세 조회 API 추가
  backend/src/main/java/yeoun/question/domain/repository/TodayQuestionRepository.java
  backend/src/main/java/yeoun/question/dto/response/TodayQuestionDetailResponse.java
  backend/src/main/java/yeoun/question/presentation/TodayQuestionController.java
  backend/src/main/java/yeoun/question/service/TodayQuestionService.java
Labels: BE, ✨ Feature

#95 [Feat] 회원 탈퇴 페이지 + 설정 페이지 수정
  frontend/src/components/dropdown/Dropdown.tsx
  frontend/src/pages/AlarmPage.tsx
  frontend/src/pages/QuestionListPage.tsx
  frontend/src/pages/SettingPage.tsx
  frontend/src/pages/UserDeletePage.tsx
  frontend/src/pages/my/MyAnswersPage.tsx
  frontend/src/pages/my/MyQuestionsPage.tsx
  frontend/src/routes/router.tsx
  frontend/src/services/api/alarm/alarmList.ts
  frontend/src/services/api/alarm/getAlarmList.ts
  frontend/src/services/api/auth/logout.ts
  frontend/src/services/api/auth/userDelete.ts
Labels: FE, ✨ Feature

#93 refactor / question-save
  backend/src/main/java/yeoun/question/service/QuestionService.java
  backend/src/main/java/yeoun/user/domain/repository/UserRepository.java
  backend/src/main/java/yeoun/user/service/UserService.java
  backend/src/main/resources/application-prod.yml
Labels: BE, 🔨 Refactor

#86 Feat/delete
  backend/src/main/java/yeoun/auth/infrastructure/CookieUtil.java
  backend/src/main/java/yeoun/comment/domain/Comment.java
  backend/src/main/java/yeoun/comment/domain/repository/CommentRepository.java
  backend/src/main/java/yeoun/comment/service/CommentService.java
  backend/src/main/java/yeoun/exception/CustomExceptionHandler.java
  backend/src/main/java/yeoun/like/domain/Like.java
  backend/src/main/java/yeoun/like/service/LikeService.java
  backend/src/main/java/yeoun/notification/service/NotificationService.java
  backend/src/main/java/yeoun/question/domain/Question.java
  backend/src/main/java/yeoun/question/dto/response/QuestionDetailResponse.java
  backend/src/main/java/yeoun/question/service/QuestionService.java
  backend/src/main/java/yeoun/user/domain/User.java
  backend/src/main/java/yeoun/user/domain/repository/UserDeleteRepository.java
  backend/src/main/java/yeoun/user/domain/repository/UserRepository.java
  backend/src/main/java/yeoun/user/presentation/UserController.java
  backend/src/main/java/yeoun/user/service/UserService.java
Labels: BE, ✨ Feature, 🔨 Refactor

#98 BUG: 내가 작성한 질문 목록 조회 시 카테고리 필터링 안되는 버그 수정
  backend/src/main/java/yeoun/question/domain/repository/QuestionRepository.java
  backend/src/main/java/yeoun/question/presentation/QuestionController.java
  backend/src/main/java/yeoun/question/service/QuestionService.java
Labels: 🐞 Bug, BE

#100 refactor : notification
  backend/src/main/java/yeoun/auth/filter/JwtAccessTokenFilter.java
  backend/src/main/java/yeoun/exception/CustomExceptionHandler.java
  backend/src/main/java/yeoun/notification/service/NotificationService.java
  backend/src/main/java/yeoun/notification/service/SseService.java
  backend/src/main/java/yeoun/notification/service/SseServiceInterface.java
  backend/src/main/resources/application-prod.yml
Labels: BE, 🔨 Refactor

#101 feat/today-question-delete
  backend/src/main/java/yeoun/question/domain/repository/QuestionHistoryRepository.java
  backend/src/main/java/yeoun/question/presentation/TodayQuestionController.java
  backend/src/main/java/yeoun/question/service/TodayQuestionService.java
Labels: BE, ✨ Feature, 🔨 Refactor

#102 Refactor/notification read
  backend/src/main/java/yeoun/notification/service/NotificationService.java
Labels: BE, 🔨 Refactor

#109 [Fix] 노션 수정사항 & UT Review Form 추가
  frontend/index.html
  frontend/src/components/backgroundBanner/BackgroundBanner.tsx
  frontend/src/components/backgroundBanner/Rating.tsx
  frontend/src/components/backgroundBanner/ReviewForm.tsx
  frontend/src/components/onboarding/OnBoardingStepOne.tsx
  frontend/src/components/onboarding/assets/step-three/CommentPage.tsx
  frontend/src/components/onboarding/assets/step-two/TodayAnswersList.svg
  frontend/src/components/onboarding/assets/step-two/TodayQuestionPage.svg
  frontend/src/components/provider/UTProvder.tsx
  frontend/src/components/provider/index.tsx
  frontend/src/components/provider/toast.tsx
  frontend/src/components/ui/QuestionPageFallback.tsx
  frontend/src/hooks/mutation/useDeleteCommentMutation.ts
  frontend/src/hooks/mutation/useUpdateCommentMutation.ts
  frontend/src/hooks/useIsMobile.ts
  frontend/src/index.css
  frontend/src/pages/AddQuestionPage.tsx
  frontend/src/pages/todayQuestion/MyTodayAnswerPage.tsx
  frontend/src/pages/todayQuestion/TodayQuestionCommentPage.tsx
  frontend/src/services/api/writeUtReview.ts
  frontend/src/store/useToastStore.ts
Labels: 🐞 Bug, FE, ✨ Feature

#110 [Feat] 알람 페이지 + 기타 수정사항
  frontend/src/App.tsx
  frontend/src/components/AlarmManager.tsx
  frontend/src/components/alarm/Alarm.tsx
  frontend/src/components/alarm/AlarmItem.tsx
  frontend/src/components/form/EditorForm.tsx
  frontend/src/components/questionList/QuestionListByDate.tsx
  frontend/src/components/questionList/QuestionListItemByDate.tsx
  frontend/src/hooks/useQuestionGroupByDate.ts
  frontend/src/index.css
  frontend/src/pages/AddQuestionPage.tsx
  frontend/src/pages/AlarmPage.tsx
  frontend/src/pages/QuestionListPage.tsx
  frontend/src/pages/SettingPage.tsx
  frontend/src/pages/UserDeletePage.tsx
  frontend/src/pages/question/CommentPage.tsx
  frontend/src/pages/question/QuestionCommentPage.tsx
  frontend/src/services/api/alarm/getNotificationList.ts
  frontend/src/services/api/auth/userDelete.ts
  frontend/src/store/useAlarmStore.ts
  frontend/src/type/auth/notification.d.ts
  frontend/src/utils/questionGroup.ts
Labels: 🐞 Bug, FE, ✨ Feature

#111 Fix/back
  backend/src/main/java/yeoun/auth/filter/JwtAccessTokenFilter.java
  backend/src/main/java/yeoun/comment/dto/response/CommentListResponse.java
  backend/src/main/java/yeoun/comment/service/CommentService.java
  backend/src/main/java/yeoun/question/domain/repository/QuestionRepository.java
Labels: BE, 🔨 Refactor

#115 [Fix] 기타 수정사항 수정
  frontend/src/components/answerList/AnswerItem.tsx
  frontend/src/components/form/CommentForm.tsx
  frontend/src/components/form/EditorForm.tsx
  frontend/src/components/questionList/QuestionListByDate.tsx
  frontend/src/components/questionList/renderQuestions.tsx
  frontend/src/pages/QuestionListPage.tsx
  frontend/src/pages/QuestionPage.tsx
  frontend/src/pages/question/CommentPage.tsx
  frontend/src/pages/question/QuestionCommentPage.tsx
  frontend/src/type/question.d.ts
Labels: 🐞 Bug, FE, ✨ Feature

#114 Refactor/back
  backend/src/main/java/yeoun/comment/domain/Comment.java
  backend/src/main/java/yeoun/comment/domain/repository/CommentRepository.java
  backend/src/main/java/yeoun/comment/dto/response/CommentResponse.java
  backend/src/main/java/yeoun/question/domain/repository/QuestionRepository.java
  backend/src/main/java/yeoun/user/domain/repository/UserDeleteRepository.java
  backend/src/main/java/yeoun/user/service/UserWithdrawer.java
Labels: BE, ✨ Feature, 🔨 Refactor
