Repository Yeoun-project/yeoun, pull requests merged in 2025-03, with the labels that each got.

#8 Feat/routing
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/main.tsx
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/LoginPage.tsx
  frontend/src/pages/MyActivityPage.tsx
  frontend/src/pages/QuestionPage.tsx
  frontend/src/pages/SettingPage.tsx
  frontend/src/routes/router.tsx
  frontend/tsconfig.json
  frontend/vite.config.ts
Labels: front

#16 feat: 오늘의 질문 선정 및 반환 API
  backend/src/main/java/com/example/demo/controller/QuestionController.java
  backend/src/main/java/com/example/demo/dto/response/TodayQuestionResponseDto.java
  backend/src/main/java/com/example/demo/entity/QuestionHistoryEntity.java
  backend/src/main/java/com/example/demo/repository/QuestionHistoryRepository.java
  backend/src/main/java/com/example/demo/repository/QuestionRepository.java
  backend/src/main/java/com/example/demo/service/QuestionService.java
  backend/src/main/java/com/example/demo/util/SecurityUtil.java
Labels: BE

#18 feat : anonymous user
  backend/src/main/java/com/example/demo/DemoApplication.java
  backend/src/main/java/com/example/demo/config/SecurityConfig.java
  backend/src/main/java/com/example/demo/controller/AuthController.java
  backend/src/main/java/com/example/demo/entity/CommentEntity.java
  backend/src/main/java/com/example/demo/entity/NotificationEntity.java
  backend/src/main/java/com/example/demo/entity/QuestionEntity.java
  backend/src/main/java/com/example/demo/entity/QuestionHistoryEntity.java
  backend/src/main/java/com/example/demo/entity/UserEntity.java
  backend/src/main/java/com/example/demo/entity/UserHistoryEntity.java
  backend/src/main/java/com/example/demo/jwt/JwtAccessTokenFilter.java
  backend/src/main/java/com/example/demo/jwt/JwtAnonymousTokenFilter.java
  backend/src/main/java/com/example/demo/jwt/JwtRefreshTokenFilter.java
  backend/src/main/java/com/example/demo/jwt/JwtUtil.java
  backend/src/main/java/com/example/demo/jwt/UserHistoryFilter.java
  backend/src/main/java/com/example/demo/repository/UserHistoryRepository.java
  backend/src/main/java/com/example/demo/repository/UserRepository.java
  backend/src/main/java/com/example/demo/service/UserHistoryService.java
  backend/src/main/java/com/example/demo/service/UserService.java
  backend/src/main/java/com/example/demo/type/Role.java
Labels: BE

#19 feat: 질문 생성 시 금지어 검사하기
  backend/build.gradle
  backend/src/main/java/com/example/demo/entity/ForbiddenWordEntity.java
  backend/src/main/java/com/example/demo/repository/ForbiddenWordRepository.java
  backend/src/main/java/com/example/demo/service/ForbiddenWordService.java
  backend/src/main/java/com/example/demo/service/QuestionService.java
  backend/src/test/java/com/example/demo/forbiddenWord/service/ForbiddenWordServiceTest.java
Labels: BE, ✨ Feature

#13 [Feat] 오늘의 질문 페이지
  frontend/.prettierrc
  frontend/index.html
  frontend/package.json
  frontend/public/fonts/ONE-Mobile-Light.woff
  frontend/public/fonts/ONE-Mobile-Title.woff
  frontend/public/icons/left.svg
  frontend/public/icons/settings.svg
  frontend/src/App.tsx
  frontend/src/assets/Icons/nav/AddQuestionIcon.tsx
  frontend/src/assets/Icons/nav/MyPageIcon.tsx
  frontend/src/assets/Icons/nav/QuestionIcon.tsx
  frontend/src/assets/Icons/nav/QuestionListIcon.tsx
  frontend/src/assets/Squre.tsx
  frontend/src/assets/react.svg
  frontend/src/components/TabNav.tsx
  frontend/src/components/circle/Circle.tsx
  frontend/src/components/common/BackArrow.tsx
  frontend/src/components/provider/index.tsx
  frontend/src/components/provider/query.tsx
  frontend/src/index.css
  frontend/src/pages/TodayQuestion/TodayQuestionCommentPage.tsx
  frontend/src/pages/TodayQuestion/TodayQuestionLayout.tsx
  frontend/src/pages/TodayQuestion/TodayQuestionPage.tsx
  frontend/src/routes/router.tsx
  frontend/src/utils/queryClient.ts
  package-lock.json
Labels: FE

#20 [Feat] 오늘의 질문 답변목록 페이지 & 답변열람 페이지 추가 & CIrcle 컴포넌트 수정
  frontend/package.json
  frontend/src/assets/Squre.tsx
  frontend/src/components/circle/Circle.tsx
  frontend/src/components/circle/CircleBottomLayer.tsx
  frontend/src/components/circle/CircleMiddleLayer.tsx
  frontend/src/components/circle/CircleProps.ts
  frontend/src/components/circle/CircleTopLayer.tsx
  frontend/src/components/circle/MainCircle.tsx
  frontend/src/components/common/BackArrow.tsx
  frontend/src/components/question/QuestionList.tsx
  frontend/src/components/question/TodayQuestionItem.tsx
  frontend/src/index.css
  frontend/src/pages/TodayQuestion/MyTodayAnswerPage.tsx
  frontend/src/pages/TodayQuestion/MyTodayAnswersPage.tsx
  frontend/src/pages/TodayQuestion/TodayQuestionCommentPage.tsx
  frontend/src/pages/TodayQuestion/TodayQuestionPage.tsx
  frontend/src/routes/router.tsx
  frontend/src/type/question.ts
  frontend/src/type/questionCategory.ts
  frontend/src/vite-env.d.ts
  frontend/vite.config.ts
  package-lock.json
Labels: FE

#21 fix: DB에 금지어 리스트가 하나도 없을 때 403을 반환하는 버그 수정
  backend/src/main/java/yeoun/question/service/ForbiddenWordService.java
Labels: 🐞 Bug, BE

#26 Develop
  .gitignore
  backend/src/main/java/yeoun/auth/SecurityConfig.java
  backend/src/main/java/yeoun/auth/filter/UserHistoryFilter.java
  backend/src/main/java/yeoun/auth/infrastructure/SecurityUtil.java
  backend/src/main/java/yeoun/comment/domain/CommentEntity.java
  backend/src/main/java/yeoun/comment/domain/repository/CommentRepository.java
  backend/src/main/java/yeoun/comment/dto/request/SaveCommentRequest.java
  backend/src/main/java/yeoun/comment/dto/response/CommentDetailResponseDto.java
  backend/src/main/java/yeoun/comment/presentation/CommentController.java
  backend/src/main/java/yeoun/comment/service/CommentService.java
  backend/src/main/java/yeoun/exception/CustomExceptionHandler.java
  backend/src/main/java/yeoun/question/domain/QuestionEntity.java
  backend/src/main/java/yeoun/question/domain/repository/QuestionRepository.java
  backend/src/main/java/yeoun/question/dto/request/AddQuestionRequest.java
  backend/src/main/java/yeoun/question/dto/response/QuestionDetailResponse.java
  backend/src/main/java/yeoun/question/presentation/QuestionController.java
  backend/src/main/java/yeoun/question/service/ForbiddenWordService.java
  backend/src/main/java/yeoun/question/service/QuestionService.java
  backend/src/main/java/yeoun/util/FormattingUtil.java
  frontend/.prettierrc
  frontend/index.html
  frontend/package.json
  frontend/public/fonts/ONE-Mobile-Light.woff
  frontend/public/fonts/ONE-Mobile-Title.woff
  frontend/public/icons/left.svg
  frontend/public/icons/settings.svg
  frontend/src/App.tsx
  frontend/src/assets/Icons/nav/AddQuestionIcon.tsx
  frontend/src/assets/Icons/nav/MyPageIcon.tsx
  frontend/src/assets/Icons/nav/QuestionIcon.tsx
  frontend/src/assets/Icons/nav/QuestionListIcon.tsx
  frontend/src/assets/Squre.tsx
  frontend/src/assets/react.svg
  frontend/src/components/TabNav.tsx
  frontend/src/components/circle/Circle.tsx
  frontend/src/components/circle/CircleBottomLayer.tsx
  frontend/src/components/circle/CircleMiddleLayer.tsx
  frontend/src/components/circle/CircleProps.ts
  frontend/src/components/circle/CircleTopLayer.tsx
  frontend/src/components/circle/MainCircle.tsx
  frontend/src/components/common/BackArrow.tsx
  frontend/src/components/provider/index.tsx
  frontend/src/components/provider/query.tsx
  frontend/src/components/question/QuestionList.tsx
  frontend/src/components/question/TodayQuestionItem.tsx
  frontend/src/index.css
  frontend/src/pages/TodayQuestion/MyTodayAnswerPage.tsx
  frontend/src/pages/TodayQuestion/MyTodayAnswersPage.tsx
  frontend/src/pages/TodayQuestion/TodayQuestionCommentPage.tsx
  frontend/src/pages/TodayQuestion/TodayQuestionLayout.tsx
  frontend/src/pages/TodayQuestion/TodayQuestionPage.tsx
  frontend/src/routes/router.tsx
  frontend/src/type/question.ts
  frontend/src/type/questionCategory.ts
  frontend/src/utils/queryClient.ts
  frontend/src/vite-env.d.ts
  frontend/vite.config.ts
  package-lock.json
Labels: 🚀 Deploy
