Repository Yeoun-project/yeoun, pull requests merged in 2025-04, with the labels that each got.

#25 feat: 질문 생성시 금지어 포함시 에러 반환에 해당 금지어 반환, 금지어 필터링 범위 -> 공백, 숫자, 특수문자
  backend/src/main/java/yeoun/question/presentation/QuestionController.java
  backend/src/main/java/yeoun/question/service/ForbiddenWordService.java
  backend/src/main/java/yeoun/question/service/QuestionService.java
  backend/src/test/java/yeoun/question/service/ForbiddenWordServiceTest.java
Labels: BE, ✨ Feature

#46 [Feat] 로그인 & 인증
  .gitignore
  frontend/src/pages/HomePage.tsx
  frontend/src/pages/TodayQuestion/TodayQuestionLayout.tsx
  frontend/src/pages/login/LoginFallback.tsx
  frontend/src/pages/login/LoginPage.tsx
  frontend/src/routes/PrivateRoute.tsx
  frontend/src/routes/router.tsx
  frontend/src/services/api/auth/checkAuth.ts
  frontend/src/services/api/auth/fetchToken.ts
  frontend/src/services/api/question/todayQuestion.ts
  frontend/src/store/useAuthStore.ts
  frontend/src/type/auth/UserType.d.ts
Labels: FE, ✨ Feature

#44 feat: 질문 목록 로드 API 기준 수정
  backend/src/main/java/yeoun/question/domain/repository/QuestionRepository.java
  backend/src/main/java/yeoun/question/presentation/QuestionController.java
  backend/src/main/java/yeoun/question/service/QuestionService.java
Labels: BE, ✨ Feature

#48 feat: 오늘의 질문 댓글 추가 API
  backend/src/main/java/yeoun/question/domain/QuestionHistory.java
  backend/src/main/java/yeoun/question/domain/repository/QuestionHistoryRepository.java
  backend/src/main/java/yeoun/question/domain/repository/QuestionRepository.java
  backend/src/main/java/yeoun/question/dto/request/AddTodayQuestionCommentRequest.java
  backend/src/main/java/yeoun/question/service/TodayQuestionService.java
Labels: BE, ✨ Feature

#51 [Feat] 모달 구현
  frontend/index.html
  frontend/public/icons/notification.svg
  frontend/src/components/NavBar.tsx
  frontend/src/components/button/BackArrowButton.tsx
  frontend/src/components/button/BasicButton.tsx
  frontend/src/components/form/CommentForm.tsx
  frontend/src/components/modal/Modal.tsx
  frontend/src/components/modal/ModalCancelButton.tsx
  frontend/src/components/modal/ModalConfirmButton.tsx
  frontend/src/components/modal/ModalSubTitle.tsx
  frontend/src/components/modal/ModalTitle.tsx
  frontend/src/components/nav/BottomTabBar.tsx
  frontend/src/components/nav/TopNavBar.tsx
  frontend/src/index.css
  frontend/src/pages/QuestionPage.tsx
  frontend/src/pages/SettingPage.tsx
  frontend/src/pages/todayQuestion/MyTodayAnswerPage.tsx
  frontend/src/pages/todayQuestion/MyTodayAnswersPage.tsx
  frontend/src/pages/todayQuestion/TodayQuestionCommentPage.tsx
  frontend/src/pages/todayQuestion/TodayQuestionPage.tsx
  frontend/src/store/useModalStore.ts
Labels: FE, ✨ Feature, 🔨 Refactor

#53 [Feat] 질문 작성 페이지
  frontend/public/icons/dropdownIcon.svg
  frontend/src/components/dropdown/Dropdown.tsx
  frontend/src/pages/AddQuestionPage.tsx
  frontend/src/routes/router.tsx
  frontend/src/services/api/question/addQuestion.ts
Labels: FE, ✨ Feature

#56 오늘의 질문 병합 충돌 중복 해결
  backend/src/main/java/yeoun/comment/domain/Comment.java
  backend/src/main/java/yeoun/comment/dto/response/CommentListResponse.java
  backend/src/main/java/yeoun/comment/presentation/CommentController.java
  backend/src/main/java/yeoun/exception/CustomExceptionHandler.java
  backend/src/main/java/yeoun/exception/ErrorCode.java
  backend/src/main/java/yeoun/question/domain/Category.java
  backend/src/main/java/yeoun/question/domain/Question.java
  backend/src/main/java/yeoun/question/domain/QuestionHistory.java
  backend/src/main/java/yeoun/question/domain/repository/CategoryResponseDao.java
  backend/src/main/java/yeoun/question/domain/repository/QuestionHistoryRepository.java
  backend/src/main/java/yeoun/question/domain/repository/QuestionRepository.java
  backend/src/main/java/yeoun/question/domain/repository/TodayQuestionRepository.java
  backend/src/main/java/yeoun/question/dto/request/AddQuestionRequest.java
  backend/src/main/java/yeoun/question/dto/request/AddTodayQuestionCommentRequest.java
  backend/src/main/java/yeoun/question/dto/response/CategoryResponse.java
  backend/src/main/java/yeoun/question/dto/response/QuestionDetailResponse.java
  backend/src/main/java/yeoun/question/dto/response/QuestionResponse.java
  backend/src/main/java/yeoun/question/dto/response/TodayQuestionDetailResponse.java
  backend/src/main/java/yeoun/question/dto/response/TodayQuestionListResponse.java
  backend/src/main/java/yeoun/question/dto/response/TodayQuestionResponse.java
  backend/src/main/java/yeoun/question/presentation/QuestionController.java
  backend/src/main/java/yeoun/question/presentation/TodayQuestionController.java
  backend/src/main/java/yeoun/question/service/QuestionService.java
  backend/src/main/java/yeoun/question/service/TodayQuestionService.java
Labels: BE, 🔨 Refactor

#58 [Feat] 질문 작성 페이지
  frontend/src/components/modal/Modal.tsx
  frontend/src/components/modal/ModalSubTitle.tsx
  frontend/src/components/modal/RegisterModal.tsx
  frontend/src/pages/AddQuestionPage.tsx
  frontend/src/services/api/question/addQuestion.ts
Labels: FE, ✨ Feature

#57 FEAT: 질문 내용 금지어 검증 API 추가
  backend/src/main/java/yeoun/question/presentation/QuestionController.java
Labels: BE, ✨ Feature

#59 FEAT: CI 백엔드 테스트 Workflow 캐시를 활용하여 속도 향상 개선
  .github/workflows/ci.yml
Labels: 🔨 Refactor, 🚀 Deploy

#60 Feat/notification
  backend/src/main/java/yeoun/notification/domain/Notification.java
  backend/src/main/java/yeoun/notification/domain/NotificationType.java
  backend/src/main/java/yeoun/notification/domain/repository/NotificationRepository.java
  backend/src/main/java/yeoun/notification/dto/response/NotificationDetailResponse.java
  backend/src/main/java/yeoun/notification/dto/response/NotificationListResponse.java
  backend/src/main/java/yeoun/notification/dto/response/NotificationResponse.java
  backend/src/main/java/yeoun/notification/presentation/NotificationController.java
  backend/src/main/java/yeoun/notification/service/NotificationService.java
  backend/src/main/java/yeoun/question/service/QuestionService.java
Labels: BE, ✨ Feature

#61 [Feat] 내 활동 페이지 UI
  frontend/public/icons/googleLogo.svg
  frontend/public/icons/kakaoLogo.svg
  frontend/public/icons/naverLogo.svg
  frontend/src/assets/Icons/GoogleIcon.tsx
  frontend/src/assets/Icons/KaKaoIcon.tsx
  frontend/src/assets/Icons/NaverIcon.tsx
  frontend/src/assets/Icons/ProfileIcon.svg
  frontend/src/components/AuthLogoIcon.tsx
  frontend/src/components/circle/Circle.tsx
  frontend/src/components/form/CommentForm.tsx
  frontend/src/pages/MyActivityPage.tsx
  frontend/src/pages/login/LoginPage.tsx
  frontend/src/pages/todayQuestion/TodayQuestionCommentPage.tsx
  frontend/src/routes/router.tsx
  frontend/src/services/api/question/todayQuestion.ts
Labels: FE

#62 Refactor/add question page
  frontend/src/components/dropdown/Dropdown.tsx
  frontend/src/pages/AddQuestionPage.tsx
Labels: FE, 🔨 Refactor

#65 [Refactor] 질문 작성 페이지 수정
  frontend/src/components/form/EditorForm.tsx
  frontend/src/components/modal/ConfirmModal.tsx
  frontend/src/components/modal/RegisterModal.tsx
  frontend/src/pages/AddQuestionPage.tsx
  frontend/src/pages/AlarmPage.tsx
Labels: FE, 🔨 Refactor

#63 FEAT: 오늘의 질문 조회 반환에 답변이 달려있는지 여부 포함
  backend/src/main/java/yeoun/question/domain/Question.java
  backend/src/main/java/yeoun/question/domain/repository/TodayQuestionRepository.java
  backend/src/main/java/yeoun/question/dto/response/QuestionDetailResponse.java
  backend/src/main/java/yeoun/question/dto/response/QuestionResponse.java
  backend/src/main/java/yeoun/question/dto/response/TodayQuestionResponse.java
  backend/src/main/java/yeoun/question/service/TodayQuestionService.java
  backend/src/main/java/yeoun/user/service/UserHistoryService.java
Labels: BE, ✨ Feature

#64 FEAT: 댓글 좋아요 상태 변경 API 추가
  backend/src/main/java/yeoun/comment/domain/Comment.java
  backend/src/main/java/yeoun/comment/service/CommentService.java
  backend/src/main/java/yeoun/like/domain/Like.java
  backend/src/main/java/yeoun/like/domain/repository/LikeRepository.java
  backend/src/main/java/yeoun/like/dto/request/LikeRequest.java
  backend/src/main/java/yeoun/like/presentation/LikeController.java
  backend/src/main/java/yeoun/like/service/LikeService.java
Labels: BE, ✨ Feature

#70 [Feat] alarm page
  frontend/src/components/alarmList/AlarmItem.tsx
  frontend/src/pages/AlarmPage.tsx
  frontend/src/services/api/alarm/getAlarmList.ts
Labels: FE, ✨ Feature

#68 Feat/logout
  backend/src/main/java/yeoun/user/domain/repository/UserHistoryRepository.java
  backend/src/main/java/yeoun/user/domain/repository/UserRepository.java
  backend/src/main/java/yeoun/user/presentation/UserController.java
  backend/src/main/java/yeoun/user/service/UserHistoryService.java
  backend/src/main/java/yeoun/user/service/UserService.java
Labels: BE, ✨ Feature

#69 Feat/delete
  backend/src/main/java/yeoun/comment/domain/Comment.java
  backend/src/main/java/yeoun/comment/presentation/CommentController.java
  backend/src/main/java/yeoun/like/domain/Like.java
  backend/src/main/java/yeoun/question/domain/Question.java
  backend/src/main/java/yeoun/question/domain/QuestionHistory.java
  backend/src/main/java/yeoun/question/dto/request/AddQuestionRequest.java
  backend/src/main/java/yeoun/question/dto/request/AddTodayQuestionCommentRequest.java
  backend/src/main/java/yeoun/question/presentation/QuestionController.java
  backend/src/main/java/yeoun/user/domain/User.java
  backend/src/main/java/yeoun/user/domain/UserHistory.java
  backend/src/main/java/yeoun/user/presentation/UserController.java
  backend/src/main/java/yeoun/user/service/UserService.java
Labels: BE, ✨ Feature
